import { Poppins } from 'next/font/google';
import "./globals.css";
import Navigation from "./component/Navbar";
import Footer from './component/Footer';
import ScrollToTopButton from './component/ScrollToTopButton';
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


export const metadata = {
  title: "Home Page",
  description: "Generated by create Home Page ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Navigation />
        {children}
        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
